blank_issues_enabled: false
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/BYTE-RANGER-Software/indy-foy/blob/main/.github/CONTRIBUTING.md
    about: Please read this before opening an issue.
