blank_issues_enabled: false
contact_links:
  - name: Questions, Support
    url: https://github.com/BYTE-RANGER-Software/indy-foy/discussions/new?category=q-a
    about: Please use Discussions for questions, support, or general feedback.

  - name: Feature Ideas
    url: https://github.com/BYTE-RANGER-Software/indy-foy/discussions/new?category=ideas
    about: Propose and discuss new ideas first in Discussions.

  - name: Contributing Guidelines
    url: https://github.com/BYTE-RANGER-Software/indy-foy/blob/main/.github/CONTRIBUTING.md
    about: Please read this before opening an issue.
