name: Milestone Task
description: "Umbrella task for a milestone; list deliverables here and convert each line into a Deliverable Task issue."
title: "[M00][Task] <Description>"
labels: []
type: task
assignees: []

body:
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Optional"
      options:
        - "P0, critical"
        - "P1, high"
        - "P2, medium"
        - "P3, low"
    validations:
      required: false

  - type: textarea
    id: goal
    attributes:
      label: "Goal"
      description: "Explain the outcome we want to achieve, not the steps."
      placeholder: "Player can enter the docks area and trigger ambient intro cutscene."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "Checklist"
      description: "List DELIVERABLES only (e.g., Create Vertical Slice, Publish Vertical Slice, Create GDD/TDD). Convert each line to an issue using '… → Convert to issue' and pick the Deliverable Task form."
      placeholder: |
        - [ ] [DEL][VS] Create Vertical Slice
        - [ ] [DEL][REL] Publish Vertical Slice build (ZIP + website link)
        - [ ] [DEL][DOC] Create GDD
        - [ ] [DEL][DOC] Create TDD
      render: markdown
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        > **Notes for maintainers**
        >
        > - Set the **Milestone** in the sidebar for this Milestone Task.
        > - Keep the title prefix `[M00][Task]`, bump the number per milestone `[M01]`, `[M02]`, and so on.
        > - In the **Checklist**, write only high-level deliverables. Do **not** list fine-grained sub-tasks here.
        > - For each checklist item use **… → Convert to issue** and choose the **Deliverable Task** form. The deliverable will then host its own checklist of **Sub-Tasks**.
        > - In each Deliverable Task, create Sub-Tasks via **… → Convert to issue** and choose the **Sub-Task** (or a specialized) form.
        > - Ensure issues are linked: Deliverable ↔ Milestone Task via **Linked issues** (“tracked by”), Sub-Tasks ↔ Deliverable likewise.
        > - Add relevant **Labels** (e.g., `Deliverable`, `Code`, `Art`, `Audio`, `Narrative`, `Level Design`, `documentation`) on the corresponding issues, auto-labeling by title prefix is handled by the workflow if enabled.
