# .github/workflows/auto-close-non-collab-issues.yml
name: Auto-close issues from non-collaborators
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const assoc = issue.author_association; // e.g. COLLABORATOR, MEMBER, OWNER, CONTRIBUTOR, NONE
            const allowed = new Set(['COLLABORATOR','MEMBER','OWNER']);
            if (!allowed.has(assoc)) {
              await github.rest.issues.createComment({
                ...context.repo, issue_number: issue.number,
                body: "Thanks! This tracker is for team work. Please use Discussions or the linked form."
              });
              await github.rest.issues.update({
                ...context.repo, issue_number: issue.number, state: "closed", state_reason: "not_planned"
              });
            }
